### ISSUE TITLE
HELP! Why when I go to the manga page, it appears error

### ISSUE THREAD

**Issue by Mangavj** [fbg13/WireManga#1]
HELP! Why when I go to the manga page, it appears error
![image](https://cloud.githubusercontent.com/assets/20301756/24702227/18fb4f9e-1a28-11e7-9f94-a151b996af36.png)
Please help me! Thanks

**Comment by fbg13** [comment]
Don't know what's happening. I just did a new install and it works just fine, also that line should only be executed in rare cases, when a cache for that manga is not found, but the cache is (re)generated when you save the manga and/or any chapter (child page) of that manga.

Did you modify any files?
Did you receive any errors while installing any of the modules?

**Comment by Mangavj** [comment]
I have not changed any files. I just deleted the default template and replaced the template with the wiremanga template. All activities on the web are normal only manga each story is faulty. Either I upload the template incorrectly. Please detailed instructions on installing the template on this code

**Comment by fbg13** [comment]
The template files from the WireMangaTheme module are copied to the templates folder when the module is activated. 

Try replacing the content of the wm_manga_single.php file in the templates folder with this https://github.com/fbg13/WireMangaTheme/blob/master/TemplateFiles/wm_manga_single.php

**Comment by Mangavj** [comment]
I tried but still failed
![image](https://cloud.githubusercontent.com/assets/20301756/24735745/99bcbbaa-1aae-11e7-8835-833537e04169.png)
Every page is normal, including chapter page only manga page is faulty
![image](https://cloud.githubusercontent.com/assets/20301756/24735797/d537af0a-1aae-11e7-91de-d6c2974f12b8.png)
![image](https://cloud.githubusercontent.com/assets/20301756/24735804/dee0f480-1aae-11e7-8f8b-f95ee094261a.png)
![image](https://cloud.githubusercontent.com/assets/20301756/24735816/e94c8998-1aae-11e7-97b0-e80aaaa93557.png)

**Comment by fbg13** [comment]
Do you have both modules activated?

**Comment by Mangavj** [comment]
yes i do

**Comment by fbg13** [comment]
Can you give me access to ftp and the PW admin?

**Comment by Mangavj** [comment]
Ok 
ftp: 
     host: bbteam.tk
     username:  u958412168
     pass: thanhomenh123
Login web : 
         http://bbteam.tk/bbteamlogin/
    username: adbbteam
      pass: adbbteam123

**Comment by fbg13** [comment]
You didn't have the WireMangaTheme module installed. It's a module just like WireManga.

The template files are copied once the module is activated and they can be updated by going to the module settings, checking the "Update Template (theme) Files" check-box and clicking submit.

**Comment by Mangavj** [comment]
This is the first time I use this source code so I do not know how to use it
Thanks for helping me
Do not know you know how to display all the images on a chapter page

**Comment by fbg13** [comment]
I'll add an option to choose between one image or all. Will try to do it tomorrow.
Have to go to sleep now.

**Comment by Mangavj** [comment]
:D oh
 good night , see you tomorrow

**Comment by fbg13** [comment]
I've added this option, you can set it either globally in the settings page or individually for each manga.

![settings](https://cloud.githubusercontent.com/assets/6839895/24768780/9b7e655c-1b0c-11e7-8364-4e8769daf977.jpg)

Go to modules page, "New" tab, click on "Add Module From URL", paste this link https://github.com/fbg13/WireMangaTheme/archive/master.zip and click "Download". Now uninstall and install back for changes to work. You need to do this since the update part is not yet finished.

**Comment by Mangavj** [comment]
Ok 
Have you tried display all the images on a chapter page ?
:)

**Comment by fbg13** [comment]
That's what I'm talking about...
Follow the steps above and you should have an option, on both the settings page and the manga edit page, to choose how to display the images.

**Comment by Mangavj** [comment]
THANKS

**Comment by Mangavj** [comment]
![image](https://cloud.githubusercontent.com/assets/20301756/24786906/0ba520b4-1b8f-11e7-9305-3efeb22ec2b0.png)
i seed only one image hide on the chapter page no all

**Comment by fbg13** [comment]
> option, on both the settings page and the manga **edit** page, to choose how to display the images

If you followed the steps you should have an option to choose how to display the images, the option is in the admin side.

In the settings page (see screenshot above) you set it site wide and in the manga edit page you can override it.

But now I think this should be decided by the user, not the site admin, how the images will be displayed

**Comment by Mangavj** [comment]
In Vietnam, people often prefer to read  all the images on one chapter page, rather than having to read each page as a foreign website. Can you guide me by images  specific how to display the entire image on a chapter page? Thank you

**Comment by fbg13** [comment]
![im](https://cloud.githubusercontent.com/assets/6839895/24823809/4116606a-1c0b-11e7-8a00-752daf3dfaa5.gif)

Uninstall the module, but make sure you check the clean up box, reinstall it, go to the reader page and you should have the wrench button as you see above.

**Comment by Mangavj** [comment]
There is a menu error, no separator Between menu A and menu B
![image](https://cloud.githubusercontent.com/assets/20301756/24826714/5cc570ac-1c66-11e7-8116-a2bcd88499d7.png)
AND ADD LOGO AT THE NAVBAR
![image](https://cloud.githubusercontent.com/assets/20301756/24826734/cd13a9dc-1c66-11e7-89c1-35c9c61840a6.png)
add the settings background for web
Finally, You can add the module Translate all words in web from english to vietnamese . PLEASE T.T

**Comment by fbg13** [comment]
I have no idea what you mean with the menus. Don't show me how something looks, show me, or explain, what you did to get that.

Also the module is not yet ready, there are still things that need to be added/fixed.

**Comment by Mangavj** [comment]
oh
